#!/usr/bin/env python3
"""Trust anchors for the console's https, as C for BearSSL.

    tools/gen-anchors.py certs/*.pem > src/core/anchors.c

An anchor is only a name and a key: BearSSL stops walking the server's chain
at the first certificate issued by one, so an intermediate CA whose key is
trusted (Let's Encrypt's Root YE, cross-signed by ISRG Root X2) saves the
checks above it -- which on a 68040 are seconds each.
"""
import sys
from cryptography import x509
from cryptography.hazmat.primitives.asymmetric import ec, rsa
from cryptography.hazmat.primitives import serialization

CURVES = {'secp256r1': 'BR_EC_secp256r1', 'secp384r1': 'BR_EC_secp384r1',
          'secp521r1': 'BR_EC_secp521r1'}


def carray(name, data):
    rows = [', '.join('0x%02X' % b for b in data[i:i + 12]) for i in range(0, len(data), 12)]
    return 'static const unsigned char %s[] = {\n    %s\n};\n' % (name, ',\n    '.join(rows))


out = ["/* Generated by tools/gen-anchors.py from the PEM files in certs/. Do not edit. */",
       '#include "anchors.h"', '']
entries = []
for n, path in enumerate(sys.argv[1:]):
    cert = x509.load_pem_x509_certificate(open(path, 'rb').read())
    dn = cert.subject.public_bytes()
    key = cert.public_key()
    out.append('/* %s */' % cert.subject.rfc4514_string())
    out.append(carray('dn%d' % n, dn))
    if isinstance(key, rsa.RSAPublicKey):
        nums = key.public_numbers()
        nb = nums.n.to_bytes((nums.n.bit_length() + 7) // 8, 'big')
        eb = nums.e.to_bytes((nums.e.bit_length() + 7) // 8, 'big')
        out.append(carray('rsa_n%d' % n, nb))
        out.append(carray('rsa_e%d' % n, eb))
        kd = ('{ BR_KEYTYPE_RSA, { .rsa = { (unsigned char *)rsa_n%d, sizeof rsa_n%d, '
              '(unsigned char *)rsa_e%d, sizeof rsa_e%d } } }' % (n, n, n, n))
    elif isinstance(key, ec.EllipticCurvePublicKey):
        q = key.public_bytes(serialization.Encoding.X962,
                             serialization.PublicFormat.UncompressedPoint)
        out.append(carray('ec_q%d' % n, q))
        kd = ('{ BR_KEYTYPE_EC, { .ec = { %s, (unsigned char *)ec_q%d, sizeof ec_q%d } } }'
              % (CURVES[key.curve.name], n, n))
    else:
        sys.exit('%s: unsupported key type' % path)
    entries.append('    { { (unsigned char *)dn%d, sizeof dn%d }, BR_X509_TA_CA, %s }' % (n, n, kd))
out.append('const br_x509_trust_anchor cdv_anchors[] = {')
out.append(',\n'.join(entries))
out.append('};')
out.append('const size_t cdv_anchors_count = sizeof cdv_anchors / sizeof cdv_anchors[0];')
print('\n'.join(out))
