#!/usr/bin/env python3
"""Generate src/core/vp8tab.h from the tables printed in RFC 6386.

The tables are read out of the RFC text rather than typed in, so a transcription
slip cannot hide in 1,056 probabilities. Usage:

    tools/gen_vp8_tables.py rfc6386.txt > src/core/vp8tab.h
"""
import re
import sys

text = open(sys.argv[1], encoding="latin-1").read().splitlines()
# Drop the page furniture that interrupts tables across page breaks.
lines = [l for l in text if "Bankoski, et al." not in l and not l.startswith("RFC 6386") and "\f" not in l]


def grab(start_pat, count):
    """Numbers following the first line matching start_pat, comments removed."""
    for i, l in enumerate(lines):
        if re.search(start_pat, l):
            body = "\n".join(lines[i + 1:i + 400])
            body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
            body = re.sub(r"//[^\n]*", "", body)
            nums = [int(x) for x in re.findall(r"-?\d+", body)[:count]]
            if len(nums) != count:
                sys.exit("short table for %s" % start_pat)
            return nums
    sys.exit("no table %s" % start_pat)


def emit(name, ctype, nums, dims):
    def nest(vals, ds, indent):
        if len(ds) == 1:
            return indent + "{ " + ", ".join("%3d" % n for n in vals) + " }"
        step = len(vals) // ds[0]
        inner = [nest(vals[i * step:(i + 1) * step], ds[1:], indent + "    ") for i in range(ds[0])]
        return indent + "{\n" + ",\n".join(inner) + "\n" + indent + "}"
    print("static const %s %s%s =" % (ctype, name, "".join("[%d]" % d for d in dims)))
    print(nest(nums, dims, "") + ";\n")


coef = grab(r"const Prob default_coeff_probs \[4\] \[8\] \[3\]", 4 * 8 * 3 * 11)
upd = grab(r"const Prob coeff_update_probs \[4\] \[8\] \[3\]", 4 * 8 * 3 * 11)
dcq = grab(r"static const int dc_qlookup\[QINDEX_RANGE\]", 128)
acq = grab(r"static const int ac_qlookup\[QINDEX_RANGE\]", 128)
mvupd = grab(r"const MV_CONTEXT vp8_mv_update_probs\[2\]", 38)
mctx = grab(r"const int vp8_mode_contexts\[6\]\[4\]", 24)

# Sanity checks against values quoted in the RFC's prose and well known.
assert coef[:33] == [128] * 33 and coef[33:39] == [253, 136, 254, 255, 228, 219], coef[:40]
assert dcq[0] == 4 and dcq[127] == 157, (dcq[0], dcq[127])
assert acq[0] == 4 and acq[127] == 284, (acq[0], acq[127])
assert mctx == [7, 1, 1, 143, 14, 18, 14, 107, 135, 64, 57, 68, 60, 56, 128, 65,
                159, 134, 128, 34, 234, 188, 128, 28]
assert all(0 < p < 256 for p in coef + upd + mvupd)
assert mvupd[:3] == [237, 246, 253], mvupd[:3]

print("/* Generated by tools/gen_vp8_tables.py from RFC 6386. Do not edit. */")
print("#ifndef VP8TAB_H\n#define VP8TAB_H\n")
emit("vp8_default_coef_probs", "unsigned char", coef, [4, 8, 3, 11])
emit("vp8_coef_update_probs", "unsigned char", upd, [4, 8, 3, 11])
emit("vp8_dc_qlookup", "short", dcq, [128])
emit("vp8_ac_qlookup", "short", acq, [128])
emit("vp8_mv_update_probs", "unsigned char", mvupd, [2, 19])
emit("vp8_mode_contexts", "unsigned char", mctx, [6, 4])
print("#endif")
