//! A minimal RustDesk agent (the controlled side) for PowerPC Mac OS X 10.4/10.5.
//!
//! Blocking I/O, no async runtime — see `Cargo.toml` for why that is the whole
//! point. Each module names the upstream file it mirrors, so the two can be
//! diffed when the protocol moves.

// Generated by build.rs from ../libs/hbb_common/protos/*.proto. Declared the
// same way hbb_common declares them (its src/lib.rs:2-5) so type paths line up
// with upstream's; protobuf-codegen-pure emits no mod.rs of its own.
#[path = "./protos/message.rs"]
#[allow(renamed_and_removed_lints, clippy::all)]
pub mod message_proto;
#[path = "./protos/rendezvous.rs"]
#[allow(renamed_and_removed_lints, clippy::all)]
pub mod rendezvous_proto;

pub mod config;
pub mod crypto;
pub mod frame;
pub mod session;
