//! A minimal RustDesk agent (the controlled side) for PowerPC Mac OS X 10.4/10.5.
//!
//! Blocking I/O, no async runtime — see `Cargo.toml` for why that is the whole
//! point. Each module names the upstream file it mirrors, so the two can be
//! diffed when the protocol moves.

// Generated by build.rs from ../libs/hbb_common/protos/*.proto. Declared the
// same way hbb_common declares them (its src/lib.rs:2-5) so type paths line up
// with upstream's; protobuf-codegen-pure emits no mod.rs of its own.
#[path = "./protos/message.rs"]
#[allow(renamed_and_removed_lints, clippy::all)]
pub mod message_proto;
#[path = "./protos/rendezvous.rs"]
#[allow(renamed_and_removed_lints, clippy::all)]
pub mod rendezvous_proto;

// Always compiled: the platform half is gated inside, so the pure change-detection
// logic stays reachable from host tests.
pub mod capture;
pub mod config;
pub mod cursor;
pub mod convert;
#[cfg(all(target_os = "macos", not(no_vpx)))]
pub mod encode;
// Always compiled, like `capture`: the FFI half is gated inside so the protocol
// decisions stay reachable from host tests.
pub mod input;
pub mod crypto;
pub mod frame;
pub mod session;
pub mod sys;
pub mod zstd_frame;
